name    'netmanagers-account'
version '0.1.3'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com'
source  'https://github.com/netmanagers/puppet-account'
summary 'Puppet module for account management'
description 'This module installs and manages users, ssh-keys and sudo entries. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
